export enum Operations {
    LOGIN = 'login',
    LOGOUT = 'logout',
    REFRESH_TOKEN = 'refresh',
    FORGOT_PASSWORD_REQ = 'forgotPasswordRequest',
    VALIDATE_OTP = 'validateOtp',
    SGS_REQUEST_COUNT = 'sgsRequestCount',
    DELETE_RECORD='deleteRecord',
    ADD_UPDATE_SCHEME_TYPES='addUpdateSchemeTypes',
    GET_SCHEME_TYPES='getSchemeTypes',
    ADD_UPDATE_SCHEMES='addUpdateSchemes',
    ADD_UPDATE_SCHEME_NAMES='addUpdateSchemeNames',
    GET_SCHEMES='getSchemes',
    GET_SCHEME_NAMES='getSchemeNames',
    ADD_UPDATE_USERS='addUpdateUsers',
    ADD_UPDATE_PAYMENT='addUpdatePayment',
    GET_USERS='getUsers',
    GET_PAYMENTS='getPayments',
    ADD_UPDATE_SCHEME_MEMBERS='addUpdateSchemeMembers',
    GET_SCHEME_MEMBERS='getSchemeMembers',
    SETTINGS='settings'
}
