export enum Operations {
    LOGIN = 'login',
    LOGOUT = 'logout',
    REFRESH_TOKEN = 'refresh',
    FORGOT_PASSWORD_REQ = 'forgotPasswordRequest',
    VALIDATE_OTP = 'validateOtp',
    SGS_REQUEST_COUNT = 'sgsRequestCount',
    DELETE_RECORD='deleteRecord',
    ADD_UPDATE_USERS='addUpdateUsers',
    GET_USERS='getUsers',
    SETTINGS='settings',
    UPLOAD_FILES='uploadFiles',
    GET_FILES='getFiles',
    ADD_UPDATE_CATEGORIES='addUpdateCategories',
    GET_CATEGORIES='getCategories',
    ADD_UPDATE_SUB_CATEGORIES='addUpdateSubCategories',
    GET_SUB_CATEGORIES='getSubCategories',
    ADD_UPDATE_PRODUCTS='addUpdateProducts',
    GET_PRODUCTS='getProducts',
    ADD_UPDATE_ORDERS='addUpdateOrders',
    GET_ORDERS='getOrders'
}
