export const DELIMITER_TYPE = [
    { label: ' , (comma)', val: ',' },
    { label: ' ; (semicolon)', val: ';' },
    { label: ' | (pipe)', val: '|' },
    { label: '# (Hash)', val: '#' },
];

export const CUSTOM_DATE_FORMAT_TYPE = [
    'DD/MM/YY',
    'DD/MM/YYYY',
    'MM/DD/YY',
    'MM/DD/YYYY',
    'YY/MM/DD',
    'YYYY/MM/DD',
    'DD/MMM/YYYY',
    'DD/MMM/YY',
    'MMM/DD/YYYY',
    'MMM/DD/YY',
    'YYYY/MMM/DD',
    'YY/MMM/DD',
    'DD-MM-YY',
    'DD-MM-YYYY',
    'MM-DD-YY',
    'MM-DD-YYYY',
    'YY-MM-DD',
    'YYYY-MM-DD',
    'DD-MMM-YYYY',
    'DD-MMM-YY',
    'MMM-DD-YYYY',
    'MMM-DD-YY',
    'YYYY-MMM-DD',
    'YY-MMM-DD',
];

export const TEMPLATE_FIELDS = [
    'Debit Account Number',
    'Beneficiary Account or IBAN',
    'Beneficiary Name',
    'Beneficiary Address Line 1',
    'Beneficiary Country',
    'Beneficiary Town',
    'Beneficiary Bank Name',
    'Beneficiary Bank Country',
    'Beneficiary Bank Location',
    'Beneficiary Bank Address',
    'Beneficiary Bank SWIFT CODE',
    'Clearing Code',
    'Payment Date',
    'Payment Currency',
    'Payment Amount',
    'Charge Type',
    'Purpose of Payment',
    'Customer Reference',
    'Txn Type',
];

export const TXN_TYPE_FIELDS = ['DFT', 'IFT', 'IST'];

export const PURPOSE_CODE_DOMESTIC_FIELDS = [
    'Trade Settlement Payment',
    'Pension Payment',
    'Court Case',
    'Securities Payment',
    'Social Security Payment',
    'Supplier Payment',
    'Tax Payment',
    'Value Added Tax Payment',
    'Credit Cards Payments',
    'Salary Payment',
    'Payments for local Banks(Transfers)',
    'Payment to Contractor',
    'Dividend-Coupon Payments',
    'Rent Payment',
    'End Of Service Benefits',
    'Termination Of Services',
    'Liability Settlements',
    'Bonus Payments',
    'Travel Allowance',
    'Insurance Premium',
    'Leave Encashment',
    'Allowances Claim',
    'Cheque Collection',
    'Tuition Fees',
    'Traning Course Fees',
    'Official Mission',
    'Treasury Payment',
    'Government Payment',
    'Bill Payment',
    'Intra Company Payment',
    'Interest',
    'Car Loan Payment',
];

export const PURPOSE_CODE_INTL_FIELDS = [
    'Merchandise Imports',
    'Freight Payment - Air',
    'Freight Payment - Land',
    'Freight Payment - Sea',
    'Merchandise Insurance /Claims payment',
    'Transportation Services - Passenger/Others',
    'Travel and Tourism',
    'Investment payments (Interest, Profits, Dividends)',
    'Other Current Transfers',
    'Repayments on Loans Received',
    'Repayments on Loans Received',
    'Drawings on Loans Extended',
    'Remittances to Bank Accounts abroad',
    'Acquisition of Portfolio Investment abroad',
    'Acquisition of Other Assets abroad',
    'Repayment of other Foreign Liabilities',
    'Payments for Services Provided - Communication Services',
    'Payments for Services Provided - Costruction Services',
    'Payments for Services Provided -Non-Merchandise Insurance services',
    'Payments for Services Provided - Financial Services',
    'Payments for Services Provided - Government Services',
    'Payments for Services Provided - Other Services',
];
